/**
 * Phase 1 table types.
 *
 * `src/integrations/supabase/types.ts` is generated by Lovable and carries the
 * banner "Do not edit it directly". It is currently EMPTY, because the Phase 1
 * migration has not been applied to the database yet — so `supabase.from(...)`
 * types every table name as `never`.
 *
 * Rather than hand-editing a generated file (which Lovable would overwrite), we
 * declare the shape Phase 1 relies on here and narrow the client once, in one
 * place. When the migration is applied and Lovable regenerates types.ts, this
 * file can simply be deleted and the import swapped — nothing else changes.
 */
import type { SupabaseClient } from "@supabase/supabase-js";

export interface ProfileRow {
  id: string;
  display_name: string | null;
  created_at: string;
  updated_at: string;
}

export interface GoalRow {
  id: string;
  user_id: string;
  domain: string;
  goal_type: string;
  name: string;
  status: string;
  priority: number;
  is_primary: boolean;
  target_value: number | string | null;
  target_unit: string | null;
  current_value: number | string | null;
  version: number;
  payload: Record<string, unknown>;
  source_metadata: Record<string, unknown>;
  content_checksum: string | null;
  op_id: string | null;
  client_created_at: string | null;
  client_updated_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Insert shapes: server-defaulted columns are optional.
 *
 * Written out explicitly rather than as `Partial<Row> & {...}` or `Omit<...>`.
 * postgrest-js resolves the upsert parameter to `never` when the Insert type is
 * an intersection or a mapped type, so these must stay plain interfaces.
 */
export interface ProfileInsert {
  id: string;
  display_name?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface GoalInsert {
  id: string;
  /** Optional: the column defaults to auth.uid() server-side. */
  user_id?: string;
  domain: string;
  goal_type: string;
  name: string;
  status: string;
  priority?: number;
  is_primary?: boolean;
  target_value?: number | string | null;
  target_unit?: string | null;
  current_value?: number | string | null;
  version?: number;
  payload?: Record<string, unknown>;
  source_metadata?: Record<string, unknown>;
  content_checksum?: string | null;
  op_id?: string | null;
  client_created_at?: string | null;
  client_updated_at?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface ProfileUpdate extends Partial<ProfileInsert> {}
export interface GoalUpdate extends Partial<GoalInsert> {}

export type Phase1Database = {
  // Must mirror the generated types.ts shape or supabase-js resolves every row
  // type to `never`.
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: [];
      };
      goals: {
        Row: GoalRow;
        Insert: GoalInsert;
        Update: GoalUpdate;
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Phase1Client = SupabaseClient<Phase1Database>;

/**
 * The single narrowing point. Lazy import keeps this module free of any client
 * construction, so importing it never touches the network or SSR.
 */
export async function phase1Client(): Promise<Phase1Client> {
  const { supabase } = await import("@/integrations/supabase/client");
  return supabase as unknown as Phase1Client;
}

/**
 * Write facades.
 *
 * Reads type correctly through Phase1Database, but postgrest-js derives the
 * upsert parameter from `Relation['Insert']`, and with the generated schema
 * still empty that resolves to `never` — so a typed `.upsert()` cannot compile
 * yet. These two functions are the ONLY place that papers over it, with a
 * narrow structural type instead of `any`, so the argument is still checked
 * against the real row shape.
 *
 * Once the migration is applied and Lovable regenerates types.ts, both bodies
 * collapse to a plain `.upsert(...)` and this comment goes away.
 */
interface UpsertOptions {
  onConflict: string;
  ignoreDuplicates: boolean;
}

interface UpsertResponse {
  error: { message: string } | null;
}

interface UpsertableTable<TInsert> {
  upsert(values: TInsert[], options: UpsertOptions): PromiseLike<UpsertResponse>;
}

function upsertable<TInsert>(client: Phase1Client, table: "profiles" | "goals") {
  return client.from(table) as unknown as UpsertableTable<TInsert>;
}

/** Insert-if-absent. Never overwrites an existing profile row. */
export async function upsertProfile(
  client: Phase1Client,
  row: ProfileInsert,
): Promise<{ error: string | null }> {
  const { error } = await upsertable<ProfileInsert>(client, "profiles").upsert([row], {
    onConflict: "id",
    ignoreDuplicates: true,
  });
  return { error: error ? error.message : null };
}

/** Reads every goal id visible to the caller. RLS scopes this to auth.uid(). */
export async function selectGoalIds(
  client: Phase1Client,
): Promise<{ ids: string[]; error: string | null }> {
  const table = client.from("goals") as unknown as {
    select(columns: string): PromiseLike<{
      data: { id: string }[] | null;
      error: { message: string } | null;
    }>;
  };
  const { data, error } = await table.select("id");
  if (error) return { ids: [], error: error.message };
  const ids = Array.isArray(data) ? data.map((r) => r.id).filter((v) => typeof v === "string") : [];
  return { ids, error: null };
}

/** Insert-if-absent. Never overwrites an existing goal row. */
export async function upsertGoals(
  client: Phase1Client,
  rows: GoalInsert[],
): Promise<{ error: string | null }> {
  const { error } = await upsertable<GoalInsert>(client, "goals").upsert(rows, {
    onConflict: "id",
    ignoreDuplicates: true,
  });
  return { error: error ? error.message : null };
}
