/**
 * Goals catalog — metadata לכל סוג יעד.
 *
 * זה המקום היחיד שיודע:
 * - איזה יחידה משתמשים לכל סוג
 * - איזה כיוון (עולה/יורד/count/event)
 * - איזה calculation method להשתמש
 * - אילו שדות רלוונטיים / חובה
 * - שם ברירת מחדל מוצע (המשתמש רשאי לשנות)
 *
 * חשוב: המערכת לא ממציאה ערכי יעד או תאריכים — רק שם מוצע.
 */
import type { CalculationMethod, GoalDirection, GoalDomain, GoalPeriod, GoalType } from "./types";

export interface GoalTypeSpec {
  id: GoalType;
  domain: GoalDomain;
  label_he: string;
  description_he: string;
  default_unit: string;
  direction: GoalDirection;
  calculation_method: CalculationMethod;
  /** האם היעד דורש target_date. */
  requires_target_date: boolean;
  /** האם היעד דורש קישור לתרגיל. */
  requires_exercise: boolean;
  /** האם היעד דורש קישור לתבנית. */
  requires_template: boolean;
  /** האם היעד דורש קישור למסלול. */
  requires_route: boolean;
  /** האם היעד דורש ערך משני (למשל משקל ב־reps_at_weight). */
  requires_extra_number: boolean;
  /** תווית של הערך המשני. */
  extra_number_label_he: string | null;
  /** האם יש תקופה (week/month/…) לחישוב. */
  requires_period: boolean;
  /** תקופה מוצעת אם דרוש (המשתמש יכול לשנות). */
  suggested_period: GoalPeriod | null;
  /** האם baseline רלוונטי לצורך progress. */
  uses_baseline: boolean;
  /** האם target_value נדרש (custom_manual לא בהכרח). */
  requires_target_value: boolean;
  /** האם המשתמש מזין current באופן ידני (במקום חישוב). */
  manual_current: boolean;
}

export const GOAL_TYPE_CATALOG: Record<GoalType, GoalTypeSpec> = {
  // -------- Running --------
  run_distance_total: {
    id: "run_distance_total",
    domain: "running",
    label_he: "מרחק כולל להשלמה",
    description_he: "צבירה של מרחק ריצה עד להשגת יעד. לדוגמה: 100 ק״מ חודש הבא.",
    default_unit: "ק״מ",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  run_event_completion: {
    id: "run_event_completion",
    domain: "running",
    label_he: "השלמת אירוע בתאריך",
    description_he: "אירוע ריצה עתידי (חצי מרתון, 10 ק״מ). מציג ספירה לאחור בלבד.",
    default_unit: "אירוע",
    direction: "event",
    calculation_method: "event_no_progress",
    requires_target_date: true,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: false,
    requires_target_value: false,
    manual_current: true,
  },
  run_time_for_distance: {
    id: "run_time_for_distance",
    domain: "running",
    label_he: "זמן יעד למרחק",
    description_he: "לרוץ מרחק נתון בזמן יעד. ערך נמוך יותר = טוב יותר.",
    default_unit: "שניות",
    direction: "decreasing",
    calculation_method: "linear_decreasing",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: true,
    extra_number_label_he: "מרחק (מטרים)",
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  run_pace_for_distance: {
    id: "run_pace_for_distance",
    domain: "running",
    label_he: "קצב יעד למרחק",
    description_he: "קצב (שניות לק״מ) למרחק נתון. ערך נמוך יותר = טוב יותר.",
    default_unit: "שנ׳/ק״מ",
    direction: "decreasing",
    calculation_method: "linear_decreasing",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: true,
    extra_number_label_he: "מרחק (מטרים)",
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  run_weekly_distance: {
    id: "run_weekly_distance",
    domain: "running",
    label_he: "מרחק שבועי",
    description_he: "סכום ק״מ בשבוע קלנדרי (א׳–שבת).",
    default_unit: "ק״מ",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "week",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  run_monthly_distance: {
    id: "run_monthly_distance",
    domain: "running",
    label_he: "מרחק חודשי",
    description_he: "סכום ק״מ בחודש קלנדרי.",
    default_unit: "ק״מ",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  run_count_in_period: {
    id: "run_count_in_period",
    domain: "running",
    label_he: "מספר ריצות בתקופה",
    description_he: "כמה ריצות בתקופה שבחרת.",
    default_unit: "ריצות",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  run_cumulative_time: {
    id: "run_cumulative_time",
    domain: "running",
    label_he: "זמן ריצה מצטבר",
    description_he: "סכום זמן ריצה בתקופה.",
    default_unit: "דקות",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  run_custom: {
    id: "run_custom",
    domain: "running",
    label_he: "יעד ריצה מותאם",
    description_he: "יעד שהמשתמש מנהל ידנית — הזנת current עצמאית.",
    default_unit: "יחידות",
    direction: "increasing",
    calculation_method: "custom_manual",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: true,
  },
  // -------- Gym --------
  gym_exercise_top_weight: {
    id: "gym_exercise_top_weight",
    domain: "gym",
    label_he: "משקל בתרגיל",
    description_he: "משקל שיא בתרגיל מסוים (מכל סטי העבודה).",
    default_unit: "kg",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  gym_reps_at_weight: {
    id: "gym_reps_at_weight",
    domain: "gym",
    label_he: "חזרות במשקל מסוים",
    description_he: "מספר חזרות בסט יחיד במשקל נתון.",
    default_unit: "חזרות",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: true,
    extra_number_label_he: "משקל (kg)",
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  gym_estimated_1rm: {
    id: "gym_estimated_1rm",
    domain: "gym",
    label_he: "1RM מוערך",
    description_he: "1RM מחושב מסטי עבודה (Epley/Brzycki). לא ניסיון 1RM אמיתי.",
    default_unit: "kg",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  gym_sessions_in_period: {
    id: "gym_sessions_in_period",
    domain: "gym",
    label_he: "אימונים בתקופה",
    description_he: "מספר אימוני חדר כושר שהושלמו בתקופה.",
    default_unit: "אימונים",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  gym_template_completions: {
    id: "gym_template_completions",
    domain: "gym",
    label_he: "השלמת תבנית X פעמים",
    description_he: "מספר פעמים שאימון נבנה מתבנית מסוימת הושלם.",
    default_unit: "פעמים",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: true,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  gym_set_completion_rate: {
    id: "gym_set_completion_rate",
    domain: "gym",
    label_he: "שיעור השלמת סטים",
    description_he: "אחוז הסטים שהושלמו מהסטים המתוכננים בתקופה.",
    default_unit: "%",
    direction: "increasing",
    calculation_method: "rate_percentage",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  gym_custom_metric: {
    id: "gym_custom_metric",
    domain: "gym",
    label_he: "מדד מותאם",
    description_he: "מדד חופשי מקושר לתרגיל — המשתמש מזין ערך נוכחי.",
    default_unit: "יחידות",
    direction: "increasing",
    calculation_method: "custom_manual",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: true,
  },
  gym_custom: {
    id: "gym_custom",
    domain: "gym",
    label_he: "יעד כוח מותאם",
    description_he: "יעד חופשי — המשתמש מנהל current בעצמו.",
    default_unit: "יחידות",
    direction: "increasing",
    calculation_method: "custom_manual",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: true,
  },
  // -------- Home --------
  home_consecutive_reps: {
    id: "home_consecutive_reps",
    domain: "home",
    label_he: "חזרות רצופות בסט",
    description_he:
      "הכי הרבה חזרות רצופות בסט יחיד לתרגיל בית (שכיבות סמיכה, כפיפות בטן וכד').",
    default_unit: "חזרות",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  home_hold_seconds: {
    id: "home_hold_seconds",
    domain: "home",
    label_he: "משך אחזקה",
    description_he: "משך אחזקה בשניות בסט (פלאנק, וכד').",
    default_unit: "שניות",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  home_total_reps_in_session: {
    id: "home_total_reps_in_session",
    domain: "home",
    label_he: "סך חזרות באימון",
    description_he: "סך החזרות בתרגיל מקושר באימון בית יחיד (המקסימלי האחרון).",
    default_unit: "חזרות",
    direction: "increasing",
    calculation_method: "linear_increasing",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: false,
  },
  home_sessions_in_period: {
    id: "home_sessions_in_period",
    domain: "home",
    label_he: "אימונים בתקופה",
    description_he: "אימוני בית שהושלמו בתקופה.",
    default_unit: "אימונים",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  home_sets_in_period: {
    id: "home_sets_in_period",
    domain: "home",
    label_he: "סטים בתקופה",
    description_he: "סטים שהושלמו באימוני בית בתקופה.",
    default_unit: "סטים",
    direction: "count",
    calculation_method: "count_over_target",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: true,
    suggested_period: "month",
    uses_baseline: false,
    requires_target_value: true,
    manual_current: false,
  },
  home_reps_per_minute: {
    id: "home_reps_per_minute",
    domain: "home",
    label_he: "חזרות לדקה",
    description_he: "קצב חזרות לדקה בסט מקושר לתרגיל.",
    default_unit: "חזרות/דקה",
    direction: "increasing",
    calculation_method: "custom_manual",
    requires_target_date: false,
    requires_exercise: true,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: true,
  },
  home_custom: {
    id: "home_custom",
    domain: "home",
    label_he: "יעד בית מותאם",
    description_he: "יעד חופשי — המשתמש מנהל current בעצמו.",
    default_unit: "יחידות",
    direction: "increasing",
    calculation_method: "custom_manual",
    requires_target_date: false,
    requires_exercise: false,
    requires_template: false,
    requires_route: false,
    requires_extra_number: false,
    extra_number_label_he: null,
    requires_period: false,
    suggested_period: null,
    uses_baseline: true,
    requires_target_value: true,
    manual_current: true,
  },
};

export function listGoalTypesByDomain(domain: "running" | "gym" | "home"): GoalTypeSpec[] {
  return Object.values(GOAL_TYPE_CATALOG).filter((s) => s.domain === domain);
}

export function getGoalTypeSpec(type: GoalType): GoalTypeSpec {
  return GOAL_TYPE_CATALOG[type];
}
