/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as RunningRouteImport } from './routes/running'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GymRouteImport } from './routes/gym'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunningNewRouteImport } from './routes/running.new'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as HomeNewRouteImport } from './routes/home.new'
import { Route as GymNewRouteImport } from './routes/gym.new'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningNewRoute = RunningNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RunningRoute,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocationsRoute,
} as any)
const HomeNewRoute = HomeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HomeRoute,
} as any)
const GymNewRoute = GymNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GymRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/new': typeof RunningNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/new': typeof RunningNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/new': typeof RunningNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/new'
  id:
    | '__root__'
    | '/'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GymRoute: typeof GymRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  LocationsRoute: typeof LocationsRouteWithChildren
  MoreRoute: typeof MoreRoute
  RunningRoute: typeof RunningRouteWithChildren
  TrashRoute: typeof TrashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/new': {
      id: '/running/new'
      path: '/new'
      fullPath: '/running/new'
      preLoaderRoute: typeof RunningNewRouteImport
      parentRoute: typeof RunningRoute
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/home/new': {
      id: '/home/new'
      path: '/new'
      fullPath: '/home/new'
      preLoaderRoute: typeof HomeNewRouteImport
      parentRoute: typeof HomeRoute
    }
    '/gym/new': {
      id: '/gym/new'
      path: '/new'
      fullPath: '/gym/new'
      preLoaderRoute: typeof GymNewRouteImport
      parentRoute: typeof GymRoute
    }
  }
}

interface GymRouteChildren {
  GymNewRoute: typeof GymNewRoute
}

const GymRouteChildren: GymRouteChildren = {
  GymNewRoute: GymNewRoute,
}

const GymRouteWithChildren = GymRoute._addFileChildren(GymRouteChildren)

interface HomeRouteChildren {
  HomeNewRoute: typeof HomeNewRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeNewRoute: HomeNewRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface LocationsRouteChildren {
  LocationsIdRoute: typeof LocationsIdRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsIdRoute: LocationsIdRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface RunningRouteChildren {
  RunningNewRoute: typeof RunningNewRoute
}

const RunningRouteChildren: RunningRouteChildren = {
  RunningNewRoute: RunningNewRoute,
}

const RunningRouteWithChildren =
  RunningRoute._addFileChildren(RunningRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GymRoute: GymRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  LocationsRoute: LocationsRouteWithChildren,
  MoreRoute: MoreRoute,
  RunningRoute: RunningRouteWithChildren,
  TrashRoute: TrashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
