/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as MoreRouteImport } from './routes/more'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as RunningIndexRouteImport } from './routes/running.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as GymIndexRouteImport } from './routes/gym.index'
import { Route as GoalsIndexRouteImport } from './routes/goals.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as BackupIndexRouteImport } from './routes/backup.index'
import { Route as TreadmillsIdRouteImport } from './routes/treadmills.$id'
import { Route as RunningRoutesRouteImport } from './routes/running.routes'
import { Route as RunningHistoryRouteImport } from './routes/running.history'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as HomeNewRouteImport } from './routes/home.new'
import { Route as GymNewRouteImport } from './routes/gym.new'
import { Route as GymCompareRouteImport } from './routes/gym.compare'
import { Route as GoalsNewRouteImport } from './routes/goals.new'
import { Route as GoalsIdRouteImport } from './routes/goals.$id'
import { Route as TemplatesIdIndexRouteImport } from './routes/templates.$id.index'
import { Route as SessionsIdIndexRouteImport } from './routes/sessions.$id.index'
import { Route as RunningNewIndexRouteImport } from './routes/running.new.index'
import { Route as RunningGoalsIndexRouteImport } from './routes/running.goals.index'
import { Route as RunningIdIndexRouteImport } from './routes/running.$id.index'
import { Route as HomeTemplatesIndexRouteImport } from './routes/home.templates.index'
import { Route as HomeQuickIndexRouteImport } from './routes/home.quick.index'
import { Route as HomeHistoryIndexRouteImport } from './routes/home.history.index'
import { Route as HomeGoalsIndexRouteImport } from './routes/home.goals.index'
import { Route as GymHistoryIndexRouteImport } from './routes/gym.history.index'
import { Route as GymGoalsIndexRouteImport } from './routes/gym.goals.index'
import { Route as ExercisesIdIndexRouteImport } from './routes/exercises.$id.index'
import { Route as TemplatesIdHistoryRouteImport } from './routes/templates.$id.history'
import { Route as TemplatesIdEditRouteImport } from './routes/templates.$id.edit'
import { Route as SessionsIdSummaryRouteImport } from './routes/sessions.$id.summary'
import { Route as RunningNewTypeRouteImport } from './routes/running.new.$type'
import { Route as RunningGoalsNewRouteImport } from './routes/running.goals.new'
import { Route as RunningIdEditRouteImport } from './routes/running.$id.edit'
import { Route as HomeQuickExerciseIdRouteImport } from './routes/home.quick.$exerciseId'
import { Route as HomeHistoryIdRouteImport } from './routes/home.history.$id'
import { Route as HomeGoalsNewRouteImport } from './routes/home.goals.new'
import { Route as GymHistoryIdRouteImport } from './routes/gym.history.$id'
import { Route as GymGoalsNewRouteImport } from './routes/gym.goals.new'
import { Route as ExercisesIdHistoryRouteImport } from './routes/exercises.$id.history'
import { Route as RunningGoalsIdIndexRouteImport } from './routes/running.goals.$id.index'
import { Route as HomeTemplatesIdIndexRouteImport } from './routes/home.templates.$id.index'
import { Route as HomeSessionsIdIndexRouteImport } from './routes/home.sessions.$id.index'
import { Route as HomeGoalsIdIndexRouteImport } from './routes/home.goals.$id.index'
import { Route as GymGoalsIdIndexRouteImport } from './routes/gym.goals.$id.index'
import { Route as RunningGoalsIdEditRouteImport } from './routes/running.goals.$id.edit'
import { Route as HomeTemplatesIdEditRouteImport } from './routes/home.templates.$id.edit'
import { Route as HomeSessionsIdSummaryRouteImport } from './routes/home.sessions.$id.summary'
import { Route as HomeGoalsIdEditRouteImport } from './routes/home.goals.$id.edit'
import { Route as GymGoalsIdEditRouteImport } from './routes/gym.goals.$id.edit'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningIndexRoute = RunningIndexRouteImport.update({
  id: '/running/',
  path: '/running/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymIndexRoute = GymIndexRouteImport.update({
  id: '/gym/',
  path: '/gym/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupIndexRoute = BackupIndexRouteImport.update({
  id: '/backup/',
  path: '/backup/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreadmillsIdRoute = TreadmillsIdRouteImport.update({
  id: '/treadmills/$id',
  path: '/treadmills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoutesRoute = RunningRoutesRouteImport.update({
  id: '/running/routes',
  path: '/running/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningHistoryRoute = RunningHistoryRouteImport.update({
  id: '/running/history',
  path: '/running/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeNewRoute = HomeNewRouteImport.update({
  id: '/home/new',
  path: '/home/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GymNewRoute = GymNewRouteImport.update({
  id: '/gym/new',
  path: '/gym/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GymCompareRoute = GymCompareRouteImport.update({
  id: '/gym/compare',
  path: '/gym/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsNewRoute = GoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIdRoute = GoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdIndexRoute = TemplatesIdIndexRouteImport.update({
  id: '/templates/$id/',
  path: '/templates/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdIndexRoute = SessionsIdIndexRouteImport.update({
  id: '/sessions/$id/',
  path: '/sessions/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningNewIndexRoute = RunningNewIndexRouteImport.update({
  id: '/running/new/',
  path: '/running/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningGoalsIndexRoute = RunningGoalsIndexRouteImport.update({
  id: '/running/goals/',
  path: '/running/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningIdIndexRoute = RunningIdIndexRouteImport.update({
  id: '/running/$id/',
  path: '/running/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTemplatesIndexRoute = HomeTemplatesIndexRouteImport.update({
  id: '/home/templates/',
  path: '/home/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeQuickIndexRoute = HomeQuickIndexRouteImport.update({
  id: '/home/quick/',
  path: '/home/quick/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHistoryIndexRoute = HomeHistoryIndexRouteImport.update({
  id: '/home/history/',
  path: '/home/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGoalsIndexRoute = HomeGoalsIndexRouteImport.update({
  id: '/home/goals/',
  path: '/home/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymHistoryIndexRoute = GymHistoryIndexRouteImport.update({
  id: '/gym/history/',
  path: '/gym/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymGoalsIndexRoute = GymGoalsIndexRouteImport.update({
  id: '/gym/goals/',
  path: '/gym/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdIndexRoute = ExercisesIdIndexRouteImport.update({
  id: '/exercises/$id/',
  path: '/exercises/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdHistoryRoute = TemplatesIdHistoryRouteImport.update({
  id: '/templates/$id/history',
  path: '/templates/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdEditRoute = TemplatesIdEditRouteImport.update({
  id: '/templates/$id/edit',
  path: '/templates/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdSummaryRoute = SessionsIdSummaryRouteImport.update({
  id: '/sessions/$id/summary',
  path: '/sessions/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningNewTypeRoute = RunningNewTypeRouteImport.update({
  id: '/running/new/$type',
  path: '/running/new/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningGoalsNewRoute = RunningGoalsNewRouteImport.update({
  id: '/running/goals/new',
  path: '/running/goals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningIdEditRoute = RunningIdEditRouteImport.update({
  id: '/running/$id/edit',
  path: '/running/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeQuickExerciseIdRoute = HomeQuickExerciseIdRouteImport.update({
  id: '/home/quick/$exerciseId',
  path: '/home/quick/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHistoryIdRoute = HomeHistoryIdRouteImport.update({
  id: '/home/history/$id',
  path: '/home/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGoalsNewRoute = HomeGoalsNewRouteImport.update({
  id: '/home/goals/new',
  path: '/home/goals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GymHistoryIdRoute = GymHistoryIdRouteImport.update({
  id: '/gym/history/$id',
  path: '/gym/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GymGoalsNewRoute = GymGoalsNewRouteImport.update({
  id: '/gym/goals/new',
  path: '/gym/goals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIdHistoryRoute = ExercisesIdHistoryRouteImport.update({
  id: '/exercises/$id/history',
  path: '/exercises/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningGoalsIdIndexRoute = RunningGoalsIdIndexRouteImport.update({
  id: '/running/goals/$id/',
  path: '/running/goals/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTemplatesIdIndexRoute = HomeTemplatesIdIndexRouteImport.update({
  id: '/home/templates/$id/',
  path: '/home/templates/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSessionsIdIndexRoute = HomeSessionsIdIndexRouteImport.update({
  id: '/home/sessions/$id/',
  path: '/home/sessions/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGoalsIdIndexRoute = HomeGoalsIdIndexRouteImport.update({
  id: '/home/goals/$id/',
  path: '/home/goals/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymGoalsIdIndexRoute = GymGoalsIdIndexRouteImport.update({
  id: '/gym/goals/$id/',
  path: '/gym/goals/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningGoalsIdEditRoute = RunningGoalsIdEditRouteImport.update({
  id: '/running/goals/$id/edit',
  path: '/running/goals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTemplatesIdEditRoute = HomeTemplatesIdEditRouteImport.update({
  id: '/home/templates/$id/edit',
  path: '/home/templates/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSessionsIdSummaryRoute = HomeSessionsIdSummaryRouteImport.update({
  id: '/home/sessions/$id/summary',
  path: '/home/sessions/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeGoalsIdEditRoute = HomeGoalsIdEditRouteImport.update({
  id: '/home/goals/$id/edit',
  path: '/home/goals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GymGoalsIdEditRoute = GymGoalsIdEditRouteImport.update({
  id: '/gym/goals/$id/edit',
  path: '/gym/goals/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/more': typeof MoreRoute
  '/trash': typeof TrashRoute
  '/goals/$id': typeof GoalsIdRoute
  '/goals/new': typeof GoalsNewRoute
  '/gym/compare': typeof GymCompareRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/history': typeof RunningHistoryRoute
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/backup/': typeof BackupIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/gym/': typeof GymIndexRoute
  '/home/': typeof HomeIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/running/': typeof RunningIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$id/history': typeof ExercisesIdHistoryRoute
  '/gym/goals/new': typeof GymGoalsNewRoute
  '/gym/history/$id': typeof GymHistoryIdRoute
  '/home/goals/new': typeof HomeGoalsNewRoute
  '/home/history/$id': typeof HomeHistoryIdRoute
  '/home/quick/$exerciseId': typeof HomeQuickExerciseIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/goals/new': typeof RunningGoalsNewRoute
  '/running/new/$type': typeof RunningNewTypeRoute
  '/sessions/$id/summary': typeof SessionsIdSummaryRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/history': typeof TemplatesIdHistoryRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
  '/gym/goals/': typeof GymGoalsIndexRoute
  '/gym/history/': typeof GymHistoryIndexRoute
  '/home/goals/': typeof HomeGoalsIndexRoute
  '/home/history/': typeof HomeHistoryIndexRoute
  '/home/quick/': typeof HomeQuickIndexRoute
  '/home/templates/': typeof HomeTemplatesIndexRoute
  '/running/$id/': typeof RunningIdIndexRoute
  '/running/goals/': typeof RunningGoalsIndexRoute
  '/running/new/': typeof RunningNewIndexRoute
  '/sessions/$id/': typeof SessionsIdIndexRoute
  '/templates/$id/': typeof TemplatesIdIndexRoute
  '/gym/goals/$id/edit': typeof GymGoalsIdEditRoute
  '/home/goals/$id/edit': typeof HomeGoalsIdEditRoute
  '/home/sessions/$id/summary': typeof HomeSessionsIdSummaryRoute
  '/home/templates/$id/edit': typeof HomeTemplatesIdEditRoute
  '/running/goals/$id/edit': typeof RunningGoalsIdEditRoute
  '/gym/goals/$id/': typeof GymGoalsIdIndexRoute
  '/home/goals/$id/': typeof HomeGoalsIdIndexRoute
  '/home/sessions/$id/': typeof HomeSessionsIdIndexRoute
  '/home/templates/$id/': typeof HomeTemplatesIdIndexRoute
  '/running/goals/$id/': typeof RunningGoalsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/more': typeof MoreRoute
  '/trash': typeof TrashRoute
  '/goals/$id': typeof GoalsIdRoute
  '/goals/new': typeof GoalsNewRoute
  '/gym/compare': typeof GymCompareRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/history': typeof RunningHistoryRoute
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/backup': typeof BackupIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/goals': typeof GoalsIndexRoute
  '/gym': typeof GymIndexRoute
  '/home': typeof HomeIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/running': typeof RunningIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/exercises/$id/history': typeof ExercisesIdHistoryRoute
  '/gym/goals/new': typeof GymGoalsNewRoute
  '/gym/history/$id': typeof GymHistoryIdRoute
  '/home/goals/new': typeof HomeGoalsNewRoute
  '/home/history/$id': typeof HomeHistoryIdRoute
  '/home/quick/$exerciseId': typeof HomeQuickExerciseIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/goals/new': typeof RunningGoalsNewRoute
  '/running/new/$type': typeof RunningNewTypeRoute
  '/sessions/$id/summary': typeof SessionsIdSummaryRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/history': typeof TemplatesIdHistoryRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
  '/gym/goals': typeof GymGoalsIndexRoute
  '/gym/history': typeof GymHistoryIndexRoute
  '/home/goals': typeof HomeGoalsIndexRoute
  '/home/history': typeof HomeHistoryIndexRoute
  '/home/quick': typeof HomeQuickIndexRoute
  '/home/templates': typeof HomeTemplatesIndexRoute
  '/running/$id': typeof RunningIdIndexRoute
  '/running/goals': typeof RunningGoalsIndexRoute
  '/running/new': typeof RunningNewIndexRoute
  '/sessions/$id': typeof SessionsIdIndexRoute
  '/templates/$id': typeof TemplatesIdIndexRoute
  '/gym/goals/$id/edit': typeof GymGoalsIdEditRoute
  '/home/goals/$id/edit': typeof HomeGoalsIdEditRoute
  '/home/sessions/$id/summary': typeof HomeSessionsIdSummaryRoute
  '/home/templates/$id/edit': typeof HomeTemplatesIdEditRoute
  '/running/goals/$id/edit': typeof RunningGoalsIdEditRoute
  '/gym/goals/$id': typeof GymGoalsIdIndexRoute
  '/home/goals/$id': typeof HomeGoalsIdIndexRoute
  '/home/sessions/$id': typeof HomeSessionsIdIndexRoute
  '/home/templates/$id': typeof HomeTemplatesIdIndexRoute
  '/running/goals/$id': typeof RunningGoalsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/more': typeof MoreRoute
  '/trash': typeof TrashRoute
  '/goals/$id': typeof GoalsIdRoute
  '/goals/new': typeof GoalsNewRoute
  '/gym/compare': typeof GymCompareRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/history': typeof RunningHistoryRoute
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/backup/': typeof BackupIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/goals/': typeof GoalsIndexRoute
  '/gym/': typeof GymIndexRoute
  '/home/': typeof HomeIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/running/': typeof RunningIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/exercises/$id/history': typeof ExercisesIdHistoryRoute
  '/gym/goals/new': typeof GymGoalsNewRoute
  '/gym/history/$id': typeof GymHistoryIdRoute
  '/home/goals/new': typeof HomeGoalsNewRoute
  '/home/history/$id': typeof HomeHistoryIdRoute
  '/home/quick/$exerciseId': typeof HomeQuickExerciseIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/goals/new': typeof RunningGoalsNewRoute
  '/running/new/$type': typeof RunningNewTypeRoute
  '/sessions/$id/summary': typeof SessionsIdSummaryRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/history': typeof TemplatesIdHistoryRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
  '/gym/goals/': typeof GymGoalsIndexRoute
  '/gym/history/': typeof GymHistoryIndexRoute
  '/home/goals/': typeof HomeGoalsIndexRoute
  '/home/history/': typeof HomeHistoryIndexRoute
  '/home/quick/': typeof HomeQuickIndexRoute
  '/home/templates/': typeof HomeTemplatesIndexRoute
  '/running/$id/': typeof RunningIdIndexRoute
  '/running/goals/': typeof RunningGoalsIndexRoute
  '/running/new/': typeof RunningNewIndexRoute
  '/sessions/$id/': typeof SessionsIdIndexRoute
  '/templates/$id/': typeof TemplatesIdIndexRoute
  '/gym/goals/$id/edit': typeof GymGoalsIdEditRoute
  '/home/goals/$id/edit': typeof HomeGoalsIdEditRoute
  '/home/sessions/$id/summary': typeof HomeSessionsIdSummaryRoute
  '/home/templates/$id/edit': typeof HomeTemplatesIdEditRoute
  '/running/goals/$id/edit': typeof RunningGoalsIdEditRoute
  '/gym/goals/$id/': typeof GymGoalsIdIndexRoute
  '/home/goals/$id/': typeof HomeGoalsIdIndexRoute
  '/home/sessions/$id/': typeof HomeSessionsIdIndexRoute
  '/home/templates/$id/': typeof HomeTemplatesIdIndexRoute
  '/running/goals/$id/': typeof RunningGoalsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/more'
    | '/trash'
    | '/goals/$id'
    | '/goals/new'
    | '/gym/compare'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/history'
    | '/running/routes'
    | '/treadmills/$id'
    | '/backup/'
    | '/exercises/'
    | '/goals/'
    | '/gym/'
    | '/home/'
    | '/locations/'
    | '/running/'
    | '/templates/'
    | '/exercises/$id/history'
    | '/gym/goals/new'
    | '/gym/history/$id'
    | '/home/goals/new'
    | '/home/history/$id'
    | '/home/quick/$exerciseId'
    | '/running/$id/edit'
    | '/running/goals/new'
    | '/running/new/$type'
    | '/sessions/$id/summary'
    | '/templates/$id/edit'
    | '/templates/$id/history'
    | '/exercises/$id/'
    | '/gym/goals/'
    | '/gym/history/'
    | '/home/goals/'
    | '/home/history/'
    | '/home/quick/'
    | '/home/templates/'
    | '/running/$id/'
    | '/running/goals/'
    | '/running/new/'
    | '/sessions/$id/'
    | '/templates/$id/'
    | '/gym/goals/$id/edit'
    | '/home/goals/$id/edit'
    | '/home/sessions/$id/summary'
    | '/home/templates/$id/edit'
    | '/running/goals/$id/edit'
    | '/gym/goals/$id/'
    | '/home/goals/$id/'
    | '/home/sessions/$id/'
    | '/home/templates/$id/'
    | '/running/goals/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/more'
    | '/trash'
    | '/goals/$id'
    | '/goals/new'
    | '/gym/compare'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/history'
    | '/running/routes'
    | '/treadmills/$id'
    | '/backup'
    | '/exercises'
    | '/goals'
    | '/gym'
    | '/home'
    | '/locations'
    | '/running'
    | '/templates'
    | '/exercises/$id/history'
    | '/gym/goals/new'
    | '/gym/history/$id'
    | '/home/goals/new'
    | '/home/history/$id'
    | '/home/quick/$exerciseId'
    | '/running/$id/edit'
    | '/running/goals/new'
    | '/running/new/$type'
    | '/sessions/$id/summary'
    | '/templates/$id/edit'
    | '/templates/$id/history'
    | '/exercises/$id'
    | '/gym/goals'
    | '/gym/history'
    | '/home/goals'
    | '/home/history'
    | '/home/quick'
    | '/home/templates'
    | '/running/$id'
    | '/running/goals'
    | '/running/new'
    | '/sessions/$id'
    | '/templates/$id'
    | '/gym/goals/$id/edit'
    | '/home/goals/$id/edit'
    | '/home/sessions/$id/summary'
    | '/home/templates/$id/edit'
    | '/running/goals/$id/edit'
    | '/gym/goals/$id'
    | '/home/goals/$id'
    | '/home/sessions/$id'
    | '/home/templates/$id'
    | '/running/goals/$id'
  id:
    | '__root__'
    | '/'
    | '/more'
    | '/trash'
    | '/goals/$id'
    | '/goals/new'
    | '/gym/compare'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/history'
    | '/running/routes'
    | '/treadmills/$id'
    | '/backup/'
    | '/exercises/'
    | '/goals/'
    | '/gym/'
    | '/home/'
    | '/locations/'
    | '/running/'
    | '/templates/'
    | '/exercises/$id/history'
    | '/gym/goals/new'
    | '/gym/history/$id'
    | '/home/goals/new'
    | '/home/history/$id'
    | '/home/quick/$exerciseId'
    | '/running/$id/edit'
    | '/running/goals/new'
    | '/running/new/$type'
    | '/sessions/$id/summary'
    | '/templates/$id/edit'
    | '/templates/$id/history'
    | '/exercises/$id/'
    | '/gym/goals/'
    | '/gym/history/'
    | '/home/goals/'
    | '/home/history/'
    | '/home/quick/'
    | '/home/templates/'
    | '/running/$id/'
    | '/running/goals/'
    | '/running/new/'
    | '/sessions/$id/'
    | '/templates/$id/'
    | '/gym/goals/$id/edit'
    | '/home/goals/$id/edit'
    | '/home/sessions/$id/summary'
    | '/home/templates/$id/edit'
    | '/running/goals/$id/edit'
    | '/gym/goals/$id/'
    | '/home/goals/$id/'
    | '/home/sessions/$id/'
    | '/home/templates/$id/'
    | '/running/goals/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoreRoute: typeof MoreRoute
  TrashRoute: typeof TrashRoute
  GoalsIdRoute: typeof GoalsIdRoute
  GoalsNewRoute: typeof GoalsNewRoute
  GymCompareRoute: typeof GymCompareRoute
  GymNewRoute: typeof GymNewRoute
  HomeNewRoute: typeof HomeNewRoute
  LocationsIdRoute: typeof LocationsIdRoute
  RunningHistoryRoute: typeof RunningHistoryRoute
  RunningRoutesRoute: typeof RunningRoutesRoute
  TreadmillsIdRoute: typeof TreadmillsIdRoute
  BackupIndexRoute: typeof BackupIndexRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  GymIndexRoute: typeof GymIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  RunningIndexRoute: typeof RunningIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ExercisesIdHistoryRoute: typeof ExercisesIdHistoryRoute
  GymGoalsNewRoute: typeof GymGoalsNewRoute
  GymHistoryIdRoute: typeof GymHistoryIdRoute
  HomeGoalsNewRoute: typeof HomeGoalsNewRoute
  HomeHistoryIdRoute: typeof HomeHistoryIdRoute
  HomeQuickExerciseIdRoute: typeof HomeQuickExerciseIdRoute
  RunningIdEditRoute: typeof RunningIdEditRoute
  RunningGoalsNewRoute: typeof RunningGoalsNewRoute
  RunningNewTypeRoute: typeof RunningNewTypeRoute
  SessionsIdSummaryRoute: typeof SessionsIdSummaryRoute
  TemplatesIdEditRoute: typeof TemplatesIdEditRoute
  TemplatesIdHistoryRoute: typeof TemplatesIdHistoryRoute
  ExercisesIdIndexRoute: typeof ExercisesIdIndexRoute
  GymGoalsIndexRoute: typeof GymGoalsIndexRoute
  GymHistoryIndexRoute: typeof GymHistoryIndexRoute
  HomeGoalsIndexRoute: typeof HomeGoalsIndexRoute
  HomeHistoryIndexRoute: typeof HomeHistoryIndexRoute
  HomeQuickIndexRoute: typeof HomeQuickIndexRoute
  HomeTemplatesIndexRoute: typeof HomeTemplatesIndexRoute
  RunningIdIndexRoute: typeof RunningIdIndexRoute
  RunningGoalsIndexRoute: typeof RunningGoalsIndexRoute
  RunningNewIndexRoute: typeof RunningNewIndexRoute
  SessionsIdIndexRoute: typeof SessionsIdIndexRoute
  TemplatesIdIndexRoute: typeof TemplatesIdIndexRoute
  GymGoalsIdEditRoute: typeof GymGoalsIdEditRoute
  HomeGoalsIdEditRoute: typeof HomeGoalsIdEditRoute
  HomeSessionsIdSummaryRoute: typeof HomeSessionsIdSummaryRoute
  HomeTemplatesIdEditRoute: typeof HomeTemplatesIdEditRoute
  RunningGoalsIdEditRoute: typeof RunningGoalsIdEditRoute
  GymGoalsIdIndexRoute: typeof GymGoalsIdIndexRoute
  HomeGoalsIdIndexRoute: typeof HomeGoalsIdIndexRoute
  HomeSessionsIdIndexRoute: typeof HomeSessionsIdIndexRoute
  HomeTemplatesIdIndexRoute: typeof HomeTemplatesIdIndexRoute
  RunningGoalsIdIndexRoute: typeof RunningGoalsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/': {
      id: '/running/'
      path: '/running'
      fullPath: '/running/'
      preLoaderRoute: typeof RunningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/': {
      id: '/gym/'
      path: '/gym'
      fullPath: '/gym/'
      preLoaderRoute: typeof GymIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/': {
      id: '/backup/'
      path: '/backup'
      fullPath: '/backup/'
      preLoaderRoute: typeof BackupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treadmills/$id': {
      id: '/treadmills/$id'
      path: '/treadmills/$id'
      fullPath: '/treadmills/$id'
      preLoaderRoute: typeof TreadmillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/routes': {
      id: '/running/routes'
      path: '/running/routes'
      fullPath: '/running/routes'
      preLoaderRoute: typeof RunningRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/history': {
      id: '/running/history'
      path: '/running/history'
      fullPath: '/running/history'
      preLoaderRoute: typeof RunningHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/new': {
      id: '/home/new'
      path: '/home/new'
      fullPath: '/home/new'
      preLoaderRoute: typeof HomeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/new': {
      id: '/gym/new'
      path: '/gym/new'
      fullPath: '/gym/new'
      preLoaderRoute: typeof GymNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/compare': {
      id: '/gym/compare'
      path: '/gym/compare'
      fullPath: '/gym/compare'
      preLoaderRoute: typeof GymCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/new': {
      id: '/goals/new'
      path: '/goals/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof GoalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$id': {
      id: '/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof GoalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/': {
      id: '/templates/$id/'
      path: '/templates/$id'
      fullPath: '/templates/$id/'
      preLoaderRoute: typeof TemplatesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/': {
      id: '/sessions/$id/'
      path: '/sessions/$id'
      fullPath: '/sessions/$id/'
      preLoaderRoute: typeof SessionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/new/': {
      id: '/running/new/'
      path: '/running/new'
      fullPath: '/running/new/'
      preLoaderRoute: typeof RunningNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/goals/': {
      id: '/running/goals/'
      path: '/running/goals'
      fullPath: '/running/goals/'
      preLoaderRoute: typeof RunningGoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/$id/': {
      id: '/running/$id/'
      path: '/running/$id'
      fullPath: '/running/$id/'
      preLoaderRoute: typeof RunningIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/templates/': {
      id: '/home/templates/'
      path: '/home/templates'
      fullPath: '/home/templates/'
      preLoaderRoute: typeof HomeTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/quick/': {
      id: '/home/quick/'
      path: '/home/quick'
      fullPath: '/home/quick/'
      preLoaderRoute: typeof HomeQuickIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/history/': {
      id: '/home/history/'
      path: '/home/history'
      fullPath: '/home/history/'
      preLoaderRoute: typeof HomeHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/goals/': {
      id: '/home/goals/'
      path: '/home/goals'
      fullPath: '/home/goals/'
      preLoaderRoute: typeof HomeGoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/history/': {
      id: '/gym/history/'
      path: '/gym/history'
      fullPath: '/gym/history/'
      preLoaderRoute: typeof GymHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/goals/': {
      id: '/gym/goals/'
      path: '/gym/goals'
      fullPath: '/gym/goals/'
      preLoaderRoute: typeof GymGoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/': {
      id: '/exercises/$id/'
      path: '/exercises/$id'
      fullPath: '/exercises/$id/'
      preLoaderRoute: typeof ExercisesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/history': {
      id: '/templates/$id/history'
      path: '/templates/$id/history'
      fullPath: '/templates/$id/history'
      preLoaderRoute: typeof TemplatesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/edit': {
      id: '/templates/$id/edit'
      path: '/templates/$id/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof TemplatesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id/summary': {
      id: '/sessions/$id/summary'
      path: '/sessions/$id/summary'
      fullPath: '/sessions/$id/summary'
      preLoaderRoute: typeof SessionsIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/new/$type': {
      id: '/running/new/$type'
      path: '/running/new/$type'
      fullPath: '/running/new/$type'
      preLoaderRoute: typeof RunningNewTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/goals/new': {
      id: '/running/goals/new'
      path: '/running/goals/new'
      fullPath: '/running/goals/new'
      preLoaderRoute: typeof RunningGoalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/$id/edit': {
      id: '/running/$id/edit'
      path: '/running/$id/edit'
      fullPath: '/running/$id/edit'
      preLoaderRoute: typeof RunningIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/quick/$exerciseId': {
      id: '/home/quick/$exerciseId'
      path: '/home/quick/$exerciseId'
      fullPath: '/home/quick/$exerciseId'
      preLoaderRoute: typeof HomeQuickExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/history/$id': {
      id: '/home/history/$id'
      path: '/home/history/$id'
      fullPath: '/home/history/$id'
      preLoaderRoute: typeof HomeHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/goals/new': {
      id: '/home/goals/new'
      path: '/home/goals/new'
      fullPath: '/home/goals/new'
      preLoaderRoute: typeof HomeGoalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/history/$id': {
      id: '/gym/history/$id'
      path: '/gym/history/$id'
      fullPath: '/gym/history/$id'
      preLoaderRoute: typeof GymHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/goals/new': {
      id: '/gym/goals/new'
      path: '/gym/goals/new'
      fullPath: '/gym/goals/new'
      preLoaderRoute: typeof GymGoalsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$id/history': {
      id: '/exercises/$id/history'
      path: '/exercises/$id/history'
      fullPath: '/exercises/$id/history'
      preLoaderRoute: typeof ExercisesIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/goals/$id/': {
      id: '/running/goals/$id/'
      path: '/running/goals/$id'
      fullPath: '/running/goals/$id/'
      preLoaderRoute: typeof RunningGoalsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/templates/$id/': {
      id: '/home/templates/$id/'
      path: '/home/templates/$id'
      fullPath: '/home/templates/$id/'
      preLoaderRoute: typeof HomeTemplatesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/sessions/$id/': {
      id: '/home/sessions/$id/'
      path: '/home/sessions/$id'
      fullPath: '/home/sessions/$id/'
      preLoaderRoute: typeof HomeSessionsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/goals/$id/': {
      id: '/home/goals/$id/'
      path: '/home/goals/$id'
      fullPath: '/home/goals/$id/'
      preLoaderRoute: typeof HomeGoalsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/goals/$id/': {
      id: '/gym/goals/$id/'
      path: '/gym/goals/$id'
      fullPath: '/gym/goals/$id/'
      preLoaderRoute: typeof GymGoalsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/goals/$id/edit': {
      id: '/running/goals/$id/edit'
      path: '/running/goals/$id/edit'
      fullPath: '/running/goals/$id/edit'
      preLoaderRoute: typeof RunningGoalsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/templates/$id/edit': {
      id: '/home/templates/$id/edit'
      path: '/home/templates/$id/edit'
      fullPath: '/home/templates/$id/edit'
      preLoaderRoute: typeof HomeTemplatesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/sessions/$id/summary': {
      id: '/home/sessions/$id/summary'
      path: '/home/sessions/$id/summary'
      fullPath: '/home/sessions/$id/summary'
      preLoaderRoute: typeof HomeSessionsIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/goals/$id/edit': {
      id: '/home/goals/$id/edit'
      path: '/home/goals/$id/edit'
      fullPath: '/home/goals/$id/edit'
      preLoaderRoute: typeof HomeGoalsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym/goals/$id/edit': {
      id: '/gym/goals/$id/edit'
      path: '/gym/goals/$id/edit'
      fullPath: '/gym/goals/$id/edit'
      preLoaderRoute: typeof GymGoalsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoreRoute: MoreRoute,
  TrashRoute: TrashRoute,
  GoalsIdRoute: GoalsIdRoute,
  GoalsNewRoute: GoalsNewRoute,
  GymCompareRoute: GymCompareRoute,
  GymNewRoute: GymNewRoute,
  HomeNewRoute: HomeNewRoute,
  LocationsIdRoute: LocationsIdRoute,
  RunningHistoryRoute: RunningHistoryRoute,
  RunningRoutesRoute: RunningRoutesRoute,
  TreadmillsIdRoute: TreadmillsIdRoute,
  BackupIndexRoute: BackupIndexRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  GymIndexRoute: GymIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  RunningIndexRoute: RunningIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ExercisesIdHistoryRoute: ExercisesIdHistoryRoute,
  GymGoalsNewRoute: GymGoalsNewRoute,
  GymHistoryIdRoute: GymHistoryIdRoute,
  HomeGoalsNewRoute: HomeGoalsNewRoute,
  HomeHistoryIdRoute: HomeHistoryIdRoute,
  HomeQuickExerciseIdRoute: HomeQuickExerciseIdRoute,
  RunningIdEditRoute: RunningIdEditRoute,
  RunningGoalsNewRoute: RunningGoalsNewRoute,
  RunningNewTypeRoute: RunningNewTypeRoute,
  SessionsIdSummaryRoute: SessionsIdSummaryRoute,
  TemplatesIdEditRoute: TemplatesIdEditRoute,
  TemplatesIdHistoryRoute: TemplatesIdHistoryRoute,
  ExercisesIdIndexRoute: ExercisesIdIndexRoute,
  GymGoalsIndexRoute: GymGoalsIndexRoute,
  GymHistoryIndexRoute: GymHistoryIndexRoute,
  HomeGoalsIndexRoute: HomeGoalsIndexRoute,
  HomeHistoryIndexRoute: HomeHistoryIndexRoute,
  HomeQuickIndexRoute: HomeQuickIndexRoute,
  HomeTemplatesIndexRoute: HomeTemplatesIndexRoute,
  RunningIdIndexRoute: RunningIdIndexRoute,
  RunningGoalsIndexRoute: RunningGoalsIndexRoute,
  RunningNewIndexRoute: RunningNewIndexRoute,
  SessionsIdIndexRoute: SessionsIdIndexRoute,
  TemplatesIdIndexRoute: TemplatesIdIndexRoute,
  GymGoalsIdEditRoute: GymGoalsIdEditRoute,
  HomeGoalsIdEditRoute: HomeGoalsIdEditRoute,
  HomeSessionsIdSummaryRoute: HomeSessionsIdSummaryRoute,
  HomeTemplatesIdEditRoute: HomeTemplatesIdEditRoute,
  RunningGoalsIdEditRoute: RunningGoalsIdEditRoute,
  GymGoalsIdIndexRoute: GymGoalsIdIndexRoute,
  HomeGoalsIdIndexRoute: HomeGoalsIdIndexRoute,
  HomeSessionsIdIndexRoute: HomeSessionsIdIndexRoute,
  HomeTemplatesIdIndexRoute: HomeTemplatesIdIndexRoute,
  RunningGoalsIdIndexRoute: RunningGoalsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
