/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as RunningRouteImport } from './routes/running'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GymRouteImport } from './routes/gym'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreadmillsIdRouteImport } from './routes/treadmills.$id'
import { Route as RunningRoutesRouteImport } from './routes/running.routes'
import { Route as RunningNewRouteImport } from './routes/running.new'
import { Route as RunningHistoryRouteImport } from './routes/running.history'
import { Route as RunningIdRouteImport } from './routes/running.$id'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as HomeNewRouteImport } from './routes/home.new'
import { Route as GymNewRouteImport } from './routes/gym.new'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'
import { Route as RunningNewTypeRouteImport } from './routes/running.new.$type'
import { Route as RunningIdEditRouteImport } from './routes/running.$id.edit'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreadmillsIdRoute = TreadmillsIdRouteImport.update({
  id: '/treadmills/$id',
  path: '/treadmills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoutesRoute = RunningRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => RunningRoute,
} as any)
const RunningNewRoute = RunningNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RunningRoute,
} as any)
const RunningHistoryRoute = RunningHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => RunningRoute,
} as any)
const RunningIdRoute = RunningIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunningRoute,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocationsRoute,
} as any)
const HomeNewRoute = HomeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HomeRoute,
} as any)
const GymNewRoute = GymNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GymRoute,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)
const RunningNewTypeRoute = RunningNewTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => RunningNewRoute,
} as any)
const RunningIdEditRoute = RunningIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RunningIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/$id': typeof RunningIdRouteWithChildren
  '/running/history': typeof RunningHistoryRoute
  '/running/new': typeof RunningNewRouteWithChildren
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/new/$type': typeof RunningNewTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/$id': typeof RunningIdRouteWithChildren
  '/running/history': typeof RunningHistoryRoute
  '/running/new': typeof RunningNewRouteWithChildren
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/new/$type': typeof RunningNewTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/gym': typeof GymRouteWithChildren
  '/home': typeof HomeRouteWithChildren
  '/locations': typeof LocationsRouteWithChildren
  '/more': typeof MoreRoute
  '/running': typeof RunningRouteWithChildren
  '/trash': typeof TrashRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/gym/new': typeof GymNewRoute
  '/home/new': typeof HomeNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/running/$id': typeof RunningIdRouteWithChildren
  '/running/history': typeof RunningHistoryRoute
  '/running/new': typeof RunningNewRouteWithChildren
  '/running/routes': typeof RunningRoutesRoute
  '/treadmills/$id': typeof TreadmillsIdRoute
  '/running/$id/edit': typeof RunningIdEditRoute
  '/running/new/$type': typeof RunningNewTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/exercises/$id'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/$id'
    | '/running/history'
    | '/running/new'
    | '/running/routes'
    | '/treadmills/$id'
    | '/running/$id/edit'
    | '/running/new/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/exercises/$id'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/$id'
    | '/running/history'
    | '/running/new'
    | '/running/routes'
    | '/treadmills/$id'
    | '/running/$id/edit'
    | '/running/new/$type'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/gym'
    | '/home'
    | '/locations'
    | '/more'
    | '/running'
    | '/trash'
    | '/exercises/$id'
    | '/gym/new'
    | '/home/new'
    | '/locations/$id'
    | '/running/$id'
    | '/running/history'
    | '/running/new'
    | '/running/routes'
    | '/treadmills/$id'
    | '/running/$id/edit'
    | '/running/new/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  GymRoute: typeof GymRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  LocationsRoute: typeof LocationsRouteWithChildren
  MoreRoute: typeof MoreRoute
  RunningRoute: typeof RunningRouteWithChildren
  TrashRoute: typeof TrashRoute
  TreadmillsIdRoute: typeof TreadmillsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treadmills/$id': {
      id: '/treadmills/$id'
      path: '/treadmills/$id'
      fullPath: '/treadmills/$id'
      preLoaderRoute: typeof TreadmillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running/routes': {
      id: '/running/routes'
      path: '/routes'
      fullPath: '/running/routes'
      preLoaderRoute: typeof RunningRoutesRouteImport
      parentRoute: typeof RunningRoute
    }
    '/running/new': {
      id: '/running/new'
      path: '/new'
      fullPath: '/running/new'
      preLoaderRoute: typeof RunningNewRouteImport
      parentRoute: typeof RunningRoute
    }
    '/running/history': {
      id: '/running/history'
      path: '/history'
      fullPath: '/running/history'
      preLoaderRoute: typeof RunningHistoryRouteImport
      parentRoute: typeof RunningRoute
    }
    '/running/$id': {
      id: '/running/$id'
      path: '/$id'
      fullPath: '/running/$id'
      preLoaderRoute: typeof RunningIdRouteImport
      parentRoute: typeof RunningRoute
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/home/new': {
      id: '/home/new'
      path: '/new'
      fullPath: '/home/new'
      preLoaderRoute: typeof HomeNewRouteImport
      parentRoute: typeof HomeRoute
    }
    '/gym/new': {
      id: '/gym/new'
      path: '/new'
      fullPath: '/gym/new'
      preLoaderRoute: typeof GymNewRouteImport
      parentRoute: typeof GymRoute
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/running/new/$type': {
      id: '/running/new/$type'
      path: '/$type'
      fullPath: '/running/new/$type'
      preLoaderRoute: typeof RunningNewTypeRouteImport
      parentRoute: typeof RunningNewRoute
    }
    '/running/$id/edit': {
      id: '/running/$id/edit'
      path: '/edit'
      fullPath: '/running/$id/edit'
      preLoaderRoute: typeof RunningIdEditRouteImport
      parentRoute: typeof RunningIdRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface GymRouteChildren {
  GymNewRoute: typeof GymNewRoute
}

const GymRouteChildren: GymRouteChildren = {
  GymNewRoute: GymNewRoute,
}

const GymRouteWithChildren = GymRoute._addFileChildren(GymRouteChildren)

interface HomeRouteChildren {
  HomeNewRoute: typeof HomeNewRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeNewRoute: HomeNewRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface LocationsRouteChildren {
  LocationsIdRoute: typeof LocationsIdRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsIdRoute: LocationsIdRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

interface RunningIdRouteChildren {
  RunningIdEditRoute: typeof RunningIdEditRoute
}

const RunningIdRouteChildren: RunningIdRouteChildren = {
  RunningIdEditRoute: RunningIdEditRoute,
}

const RunningIdRouteWithChildren = RunningIdRoute._addFileChildren(
  RunningIdRouteChildren,
)

interface RunningNewRouteChildren {
  RunningNewTypeRoute: typeof RunningNewTypeRoute
}

const RunningNewRouteChildren: RunningNewRouteChildren = {
  RunningNewTypeRoute: RunningNewTypeRoute,
}

const RunningNewRouteWithChildren = RunningNewRoute._addFileChildren(
  RunningNewRouteChildren,
)

interface RunningRouteChildren {
  RunningIdRoute: typeof RunningIdRouteWithChildren
  RunningHistoryRoute: typeof RunningHistoryRoute
  RunningNewRoute: typeof RunningNewRouteWithChildren
  RunningRoutesRoute: typeof RunningRoutesRoute
}

const RunningRouteChildren: RunningRouteChildren = {
  RunningIdRoute: RunningIdRouteWithChildren,
  RunningHistoryRoute: RunningHistoryRoute,
  RunningNewRoute: RunningNewRouteWithChildren,
  RunningRoutesRoute: RunningRoutesRoute,
}

const RunningRouteWithChildren =
  RunningRoute._addFileChildren(RunningRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  GymRoute: GymRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  LocationsRoute: LocationsRouteWithChildren,
  MoreRoute: MoreRoute,
  RunningRoute: RunningRouteWithChildren,
  TrashRoute: TrashRoute,
  TreadmillsIdRoute: TreadmillsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
